INSERT INTO category (id, name)
SELECT gen_random_uuid(), new_category.name
FROM (VALUES ('Adoption'),
             ('Children'),
             ('Elder Care'),
             ('Dating'),
             ('Friendship'),
             ('Love'),
             ('Anxiety'),
             ('Life Lessons'),
             ('Career Advice'),
             ('Morning Routines'),
             ('Meditation'),
             ('Mindfulness'),
             ('Entrepreneurship'),
             ('Startups'),
             ('Management'),
             ('Content Marketing'),
             ('Leadership'),
             ('Creativity'),
             ('Coding'),
             ('Java'),
             ('Productive'),
             ('Cryptocurrency'),
             ('Devops'),
             ('Education'),
             ('Astrology'),
             ('Tourism'),
             ('Travel'),
             ('Money')) AS new_category (name);
